catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vitest: 4.1.11
  vite-plus: 0.2.2
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
